apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-train
  namespace: kubeflow
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }
---
apiVersion: v1
kind: Pod
metadata:
  name: dummy-pod-for-pvc-bind
  namespace: kubeflow
spec:
  restartPolicy: Never
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: pvc-train
  containers:
  - name: download-training-code
    image: alpine/git:latest
    env:
    volumeMounts:
    - name: pvc
      mountPath: "/home/jovyan/git-volume"
    command:
    - /bin/sh
    - -c
    - |
      echo this pod will run to bind the pvc because of a bug in argo, then it will be completed
---
apiVersion: v1
kind: Pod
metadata:
  name: download-training-code
  namespace: kubeflow
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  restartPolicy: Never
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: pvc-train
  containers:
  - name: download-training-code
    image: alpine/git:latest
    env:
    - name: MEDDASH_BRANCH_NAME
      value: "datapipelines-034"
    volumeMounts:
    - name: pvc
      mountPath: "/home/jovyan/git-volume"
    command:
    - /bin/sh
    - -c
    - |
      apk add --no-cache git 
      rm -rf /home/jovyan/git-volume/*
      git clone --branch $MEDDASH_BRANCH_NAME  https://github.com/meddash-cloud/cicd-projects-examples.git /home/jovyan/git-volume/src
      chmod -R 777 /home/jovyan/git-volume/*
---
apiVersion: v1
kind: Pod
metadata:
  name: run-jupyter-trainer
  namespace: kubeflow
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "2"
spec:
  restartPolicy: Never
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: pvc-train
  containers:
  - name: run-jupyter-trainer
    image: kubeflownotebookswg/jupyter-pytorch-full
    env:
    - name: MEDDASH_BRANCH_NAME
      value: "datapipelines-034"
    - name: MEDDASH_CLUSTER_ID
      value: "v1005r7c-bfef-4f0b-8028-99d5fdcf47de"
    volumeMounts:
    - name: pvc
      mountPath: "/home/jovyan/git-volume"
    command:
    - /bin/sh
    - -c
    - |
      cd /home/jovyan/git-volume/src/$MEDDASH_BRANCH_NAME/ && ipython 020-pipeline-step-04-run.ipynb
