---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tf-train
  namespace: kubeflow
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-download-training-code
  namespace: kubeflow
spec:
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: pvc-tf-train
  containers:
  - name: download-training-code
    image: alpine/git:latest
    env:
    - name: MEDDASH_BRANCH_NAME
      value: "datapipelines-027"
    volumeMounts:
      - name: pvc
        mountPath: "/home/jovyan/git-volume"
    command:
    - /bin/sh
    - -c
    - |
      while true; do sleep 10; done
apiVersion: batch/v1
kind: Job
metadata:
  name: download-training-code
  namespace: kubeflow
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: pvc-tf-train
  containers:
  - name: download-training-code
    image: alpine/git:latest
    env:
    - name: MEDDASH_BRANCH_NAME
      value: "datapipelines-027"
    volumeMounts:
      - name: pvc
        mountPath: "/home/jovyan/git-volume"
    command:
    - /bin/sh
    - -c
    - |
      apk add --no-cache git 
      rm -rf /home/jovyan/git-volume/*
      git clone --branch $MEDDASH_BRANCH_NAME  https://github.com/meddash-cloud/cicd-projects-examples.git /home/jovyan/git-volume/src
      chmod -R 777 /home/jovyan/git-volume/*
---
apiVersion: batch/v1
kind: Job
metadata:
  name: run-jupyter-trainer
  namespace: kubeflow
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "2"
spec:
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: pvc-tf-train

  containers:
  - name: run-jupyter-trainer
    image: jupyter/tensorflow-notebook
    env:
    - name: MEDDASH_BRANCH_NAME
      value: "datapipelines-027"
    - name: MEDDASH_CLUSTER_ID
      value: "v1005r7c-bfef-4f0b-8028-99d5fdcf47de"
    volumeMounts:
      - name: pvc
        mountPath: "/home/jovyan/git-volume"
    command:
    - /bin/sh
    - -c
    - |
      pip install  --quiet kfp==1.8.22
      ipython /home/jovyan/git-volume/src/$MEDDASH_BRANCH_NAME/030-pipeline-builder.ipynb >/tmp/jupyter-runner.output 2>&1
