apiVersion: batch/v1
kind: Job
metadata:
  name: run-jupyter-trainer
  namespace: kubeflow
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "2"
spec:
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: pvc-tf-train

  containers:
  - name: run-jupyter-trainer
    image: jupyter/tensorflow-notebook
    env:
    - name: MEDDASH_BRANCH_NAME
      value: "datapipelines-027"
    - name: MEDDASH_CLUSTER_ID
      value: "v1005r7c-bfef-4f0b-8028-99d5fdcf47de"
    volumeMounts:
      - name: pvc
        mountPath: "/home/jovyan/git-volume"
    command:
    - /bin/sh
    - -c
    - |
      pip install  --quiet kfp==1.8.22
      ipython /home/jovyan/git-volume/src/$MEDDASH_BRANCH_NAME/030-pipeline-builder.ipynb >/tmp/jupyter-runner.output 2>&1
