apiVersion: v1
kind: Service
metadata:
  name: model-service
  namespace: kubeflow
  labels:
    app: serve-train-model
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: serve-train-model

