apiVersion: batch/v1
kind: Job
metadata:
  name: download-training-code
  namespace: kubeflow
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: pvc-train
      containers:
      - name: download-training-code
        image: alpine/git:latest
        env:
        - name: MEDDASH_BRANCH_NAME
          value: "datapipelines-029"
        volumeMounts:
        - name: pvc
          mountPath: "/home/jovyan/git-volume"
        command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache git 
          rm -rf /home/jovyan/git-volume/*
          git clone --branch $MEDDASH_BRANCH_NAME  https://github.com/meddash-cloud/cicd-projects-examples.git /home/jovyan/git-volume/src
          chmod -R 777 /home/jovyan/git-volume/*
